services:
  node:
    image: node:16-alpine
    working_dir: /application
    user: "node"
    volumes:
      - .:/application
    command: npm install && npm run watch

  webserver:
    build:
      context: docker/nginx/
    depends_on:
      - php-fpm
    working_dir: /application
    user: "nginx"
    volumes:
      - .:/application

  php-fpm:
    build:
      context: docker/php-fpm/
    working_dir: /application
    user: "www-data"
    volumes:
      - .:/application
