services:
  node:
    image: node:16-alpine
    working_dir: /application
    user: "node"
    volumes:
      - .:/application
      - ../repos:/var/repos
    command: /bin/sh -c "npm ci && npm run watch"
    #command: /bin/sh -c npm start

  webserver:
    build:
      context: docker/nginx/
    depends_on:
      - php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ../repos:/var/repos


  php-fpm:
    build:
      context: docker/php-fpm/
    working_dir: /application

    volumes:
      - .:/application
      - ../repos:/var/repos

